google_sheets:
  _target_: "telegram_bot_ingestor.services.google_sheets.GoogleSheets"
  sheet_name: "реестр"
  worksheet_name: "участки"
  share_emails:
    - "konst.verner@gmail.com"
    - "olegovichaleksandr8@gmail.com"
llm:
  prompt_template:
    en: "You are given column names of a table, `text_content` and optionally `file_content`.
    Using information from `text_content` and `file_content` complete column names and return a valid json document.
    If the information is not found, use the value `null`.
    No comments and explanation are allowed. As nan value use `null`.
    column names {column_names}
    text_content {text_content}
    file_content {file_content}"
    ru: "Вам даны имена столбцов таблицы, `text_content` и, опционально, `file_content`.
    Используя информацию из `text_content` и `file_content`, заполните имена столбцов и верните допустимый документ JSON.
    Если искомой информации нет, используй значение `null`.
    Комментарии и пояснения не допускаются. В качестве значения nan используйте `null`.
    имена столбцов {column_names}
    text_content {text_content}
    file_content {file_content}"
  provider: "fireworks"
  model_name: "accounts/fireworks/models/llama-v3-70b-instruct"
