name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: global
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file
        run: |
          echo "YANDEX_API_TOKEN=${{ vars.BOT_TOKEN }}" >> .env
          echo "YANDEX_API_TOKEN=${{ env.BOT_TOKEN }}" >> .env
          echo "BOT_TOKEN=${{ vars.BOT_TOKEN }}" >> .env
          echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env
          echo "FIREWORKS_API_KEY=${{ vars.FIREWORKS_API_KEY }}" >> .env
          echo "TYPE=${{ vars.TYPE }}" >> .env
          echo "PROJECT_ID=${{ vars.PROJECT_ID }}" >> .env
          echo "PRIVATE_KEY_ID=${{ vars.PRIVATE_KEY_ID }}" >> .env
          echo "PRIVATE_KEY=${{ vars.PRIVATE_KEY }}" >> .env
          echo "CLIENT_EMAIL=${{ vars.CLIENT_EMAIL }}" >> .env
          echo "CLIENT_ID=${{ vars.CLIENT_ID }}" >> .env
          echo "TOKEN_URI=${{ vars.TOKEN_URI }}" >> .env
          echo "AUTH_URI=${{ vars.AUTH_URI }}" >> .env
          echo "AUTH_PROVIDER_X509_CERT_URL=${{ vars.AUTH_PROVIDER_X509_CERT_URL }}" >> .env
          echo "CLIENT_X509_CERT_URL=${{ vars.CLIENT_X509_CERT_URL }}" >> .env
      - name: Echo login DockerHub
        run: echo "${{ vars.DOCKERHUB_USERNAME }}" echo "${{ vars.DOCKERHUB_TOKEN }}"
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/telegram_bot_ingestor:latest

      - name: Log out from DockerHub
        run: docker logout
